version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=octofit_db
      - POSTGRES_USER=octofit_user
      - POSTGRES_PASSWORD=octofit_password
    ports:
      - "5432:5432"

  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=octofit_db
      - POSTGRES_USER=octofit_user
      - POSTGRES_PASSWORD=octofit_password
      - POSTGRES_HOST=db
      - CORS_ALLOWED_ORIGINS=http://localhost:5173
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_API_URL=http://localhost:8000/api
    depends_on:
      - web

volumes:
  postgres_data: